### ISSUE TITLE
Yuzu crashes in BOTW after latest update

### ISSUE THREAD

**Issue by Black616Angel** [flathub/org.yuzu_emu.yuzu#576]
Hello,
after the todays update I can't load my saves in BTOW.
I tried running in Vulkan an OpenGL mode, but both crashed.

System information:
```System:
  Host: pop-os Kernel: 5.17.15-76051715-generic x86_64 bits: 64 compiler: gcc
    v: 11.2.0 Desktop: GNOME 42.2 Distro: Pop!_OS 22.04 LTS
    base: Ubuntu 22.04 LTS Jammy
Machine:
  Type: Desktop Mobo: ASRock model: B450M Pro4 serial: <superuser required>
    UEFI: American Megatrends v: P3.90 date: 12/09/2019
Battery:
  Device-1: nintendo_switch_controller_battery_0005:057E:2009.0007 model: N/A
    charge: Full status: Charging
CPU:
  Info: 8-core model: AMD Ryzen 7 3700X bits: 64 type: MT MCP arch: Zen 2
    rev: 0 cache: L1: 512 KiB L2: 4 MiB L3: 32 MiB
  Speed (MHz): avg: 2277 high: 3593 min/max: 2200/4426 boost: enabled
    cores: 1: 2196 2: 2192 3: 2195 4: 2195 5: 2053 6: 2053 7: 2058 8: 3583
    9: 1863 10: 1915 11: 2195 12: 2192 13: 2052 14: 2052 15: 2053 16: 3593
    bogomips: 114988
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: NVIDIA TU106 [GeForce RTX 2060 SUPER] vendor: Gigabyte
    driver: nvidia v: 510.73.05 bus-ID: 07:00.0
  Device-2: Generalplus WEB CAM type: USB driver: snd-usb-audio,uvcvideo
    bus-ID: 5-1.2:6
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: nvidia
    gpu: nvidia resolution: 1: 1920x1080~60Hz 2: 1920x1080
  OpenGL: renderer: NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2
    v: 4.6.0 NVIDIA 510.73.05 direct render: Yes
Network:
  Device-1: Intel Wi-Fi 6 AX210/AX211/AX411 160MHz driver: iwlwifi v: kernel
    bus-ID: 04:00.0
  IF: wlp4s0 state: down mac: a4:6b:b6:3d:4b:7c
  Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    vendor: ASRock driver: r8169 v: kernel port: f000 bus-ID: 05:00.0
  IF: enp5s0 state: up speed: 1000 Mbps duplex: full mac: a8:a1:59:23:94:0c
  Device-3: NetXen Incorporated NX3031 Multifunction 1/10-Gigabit Server
  Adapter
    vendor: Hewlett-Packard NC522SFP Dual Port 10GbE driver: netxen_nic
    v: 4.0.82 port: N/A bus-ID: 06:00.0
  IF: enp6s0f0 state: down mac: 80:c1:6e:aa:d2:60
  Device-4: NetXen Incorporated NX3031 Multifunction 1/10-Gigabit Server
  Adapter
    vendor: Hewlett-Packard NC522SFP Dual Port 10GbE driver: netxen_nic
    v: 4.0.82 port: N/A bus-ID: 06:00.1
  IF: enp6s0f1 state: down mac: 80:c1:6e:aa:d2:64
  IF-ID-1: anbox0 state: down mac: 76:3d:80:17:0e:3c
  IF-ID-2: docker0 state: down mac: 02:42:f3:9a:6d:cb
  IF-ID-3: virbr0 state: down mac: 52:54:00:41:f6:27
Drives:
  Local Storage: total: 8.3 TiB used: 2.5 TiB (30.1%)
Info:
  Processes: 440 Uptime: 55m Memory: 15.55 GiB used: 3.76 GiB (24.2%)
  Init: systemd runlevel: 5 Compilers: gcc: 11.2.0 Packages: 2550 Shell: fish
  v: 3.3.1 inxi: 3.3.13
```

Logfile:
[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9121200/yuzu_log.txt)

**Comment by jasondyoungberg** [comment]
I'm also having issues with botw. It won't get past the white flash durring the opening cutscene.
[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9124954/yuzu_log.txt)
```
System:
  Host: jason-ubuntu Kernel: 5.15.0-40-generic x86_64 bits: 64 compiler: gcc
    v: 11.2.0 Desktop: GNOME 42.2 Distro: Ubuntu 22.04 LTS (Jammy Jellyfish)
Machine:
  Type: Laptop System: Micro-Star product: GF65 Thin 9SD v: REV:1.0
    serial: <superuser required>
  Mobo: Micro-Star model: MS-16W1 v: REV:1.0 serial: <superuser required>
    UEFI: American Megatrends v: E16W1IMS.10B date: 05/19/2020
Battery:
  ID-1: BAT1 charge: 47.7 Wh (95.2%) condition: 50.1/51.3 Wh (97.8%)
    volts: 12.6 min: 11.4 model: MSI Corp. MS-16W1 status: N/A
  Device-1: hidpp_battery_0 model: Logitech Wireless Mouse M510
    charge: 55% (should be ignored) status: Discharging
CPU:
  Info: 6-core model: Intel Core i7-9750H bits: 64 type: MT MCP
    arch: Coffee Lake rev: D cache: L1: 384 KiB L2: 1.5 MiB L3: 12 MiB
  Speed (MHz): avg: 4154 high: 4199 min/max: 800/4500 cores: 1: 4196
    2: 4068 3: 4189 4: 4160 5: 4176 6: 4164 7: 4178 8: 4014 9: 4156 10: 4156
    11: 4195 12: 4199 bogomips: 62399
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel CoffeeLake-H GT2 [UHD Graphics 630] vendor: Micro-Star MSI
    driver: i915 v: kernel bus-ID: 00:02.0
  Device-2: NVIDIA TU116M [GeForce GTX 1660 Ti Mobile]
    vendor: Micro-Star MSI driver: nvidia v: 510.73.05 bus-ID: 01:00.0
  Display: x11 server: X.Org v: 1.21.1.3 driver: X:
    loaded: modesetting,nvidia unloaded: fbdev,nouveau,vesa gpu: i915
    resolution: 1: 2560x1080 2: 1920x1080~144Hz
  OpenGL: renderer: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
    v: 4.6.0 NVIDIA 510.73.05 direct render: Yes
Network:
  Device-1: Intel Cannon Lake PCH CNVi WiFi driver: iwlwifi v: kernel
    bus-ID: 00:14.3
  IF: wlo1 state: up mac: 94:e7:0b:88:2b:fb
  Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet
    vendor: Micro-Star MSI driver: r8169 v: kernel port: 3000 bus-ID: 04:00.0
  IF: enp4s0 state: down mac: 2c:f0:5d:b1:9d:fc
  IF-ID-1: docker0 state: down mac: 02:42:34:e3:a3:5b
Drives:
  Local Storage: total: 1.4 TiB used: 609.32 GiB (42.6%)
Info:
  Processes: 397 Uptime: 4d 6h 38m Memory: 31.19 GiB used: 8.31 GiB (26.6%)
  Init: systemd runlevel: 5 Compilers: gcc: 11.2.0 clang: 14.0.0-1ubuntu1
  Packages: 2795 Shell: Bash v: 5.1.16 inxi: 3.3.13
```

**Comment by jasondyoungberg** [comment]
I installed yuzu from the appimage, and that worked, so it has to be something to do with flatpak

**Comment by ljmc2000** [comment]
I think this and 3 other issues are a problem with flatpak. I did a diff between 1089 and 1090 (which is the boundry between working and not working) and there was no suspicious differences, so I bet it's some change in default permissions for file writing on the build server.

For now try running `flatpak update --commit=003fb91f0bd1b3a23e6111f9d602cb124e74f693ce010a402e3b949c817171dc org.yuzu_emu.yuzu` to roll back to 1089 which is still working

**Comment by liushuyu** [comment]
Hi all, 

Thank you for your report. We have identified the issue and will publish a fix soon.

The issue is in the `dynarmic` CPU JIT module and will only affect the Flatpak version due to the way how Flatpak version is compiled.

You can temporarily use the AppImage version or downgrade to 1089 as a workaround. Sorry for the inconvenience.

**Comment by liushuyu** [comment]
Hi there,

We have (hopefully) fixed the issue in the mainline 1094 version.

I have submitted the new build to FlatHub. It may take a while for FlatHub to make the new release available.

Please test if this new version fixed your issue.

**Comment by ljmc2000** [comment]
updated to 1094. BOTW crashes on loading screen. Sorry, the patch doesn't seem to have fixed the problem

**Comment by liushuyu** [comment]
> updated to 1094. BOTW crashes on loading screen. Sorry, the patch doesn't seem to have fixed the problem


Can you help us debug this issue?

The instructions are as follows:

1. Install Flatpak SDK: `flatpak install org.kde.Sdk//5.15-21.08`
2. Switch back to the mainline 1094 version
3. Install yuzu debug symbols: `flatpak install org.yuzu_emu.yuzu.Debug`
4. In the terminal, run `flatpak run --command=sh --devel org.yuzu_emu.yuzu`
5. Run `gdb /app/bin/yuzu` and wait for the `(gdb)` prompt to show up
6. Type <kbd>r</kbd> and hit <kbd>Enter</kbd> to launch yuzu under the debugger
7. When yuzu crashes or freezes, switch back to the terminal and type `bt` at the `(gdb)` prompt
8. If `gdb` tells you to page the output, type <kbd>c</kbd> to show all the output
9. Copy and paste all the output to this post
10. Type <kbd>q</kbd> to kill both the debugger and crashed yuzu

Thank you!

**Comment by ljmc2000** [comment]
Oh, ya think it's funny to set some breakpoints and then leave it to me to figure out what you did and why it just kinda froze? Ya think it's funny to tell me to copy and paste almost 1000 lines rather than just pipe everything into tee in the first place?
[here's](https://github.com/flathub/org.yuzu_emu.yuzu/files/9130688/yuzu-gdb.log) your debugger output. sorry it took so long.

**Comment by ljmc2000** [comment]
Next to dolphin, this is one of the best programmed emulators I've ever seen, (from someone who has never seen the source code and wouldn't know what I was looking at if I saw it). You don't need to tell me what an undertaking you're involved in. But if I hadn't seen a debugger before, I would have just assumed the program crashed, and I'd be uploading pretty useless logs. I make these complaints because the next person asked for a debugging log mightn't be so quick to diagnose the problem. Good luck bug hunting soldier.

**Comment by liushuyu** [comment]
Hi all,

We have identified multiple causes that may have led to the issue. We have fixed one of the issues in the mainline 1096 version.

I have submitted the new build to FlatHub. It may take a while for FlatHub to make the new release available.

Note that the cause of your crash may be different from the other people in this thread. Please test if this new version fixed your issue. If this version still does not fix your issue: don't worry; we are coming up with a speculative fix for the other issues (which will take a while).

Thank you

**Comment by Black616Angel** [comment]
Hey,
so my game is still crashing.
I have the version 1096.

[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9140993/yuzu_log.txt)

I did your debug-steps and got like 20+ SIGSEGVs.
[log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9141040/log.txt)
Some errors are german, sorry for that.
"Kein passender Prozess gefunden." means "No matching process found."

**Comment by liushuyu** [comment]
Hi all,

We now have a speculative fix for the issue. Since this is a speculative fix, we/I have prepared a test version for you: https://github.com/flathub/org.yuzu_emu.yuzu/pull/587#issuecomment-1189641450.

Please test if this fix at least helps with the crash (e.g. if it delays the crash or make the crash harder to reproduce).

Thank you

**Comment by ljmc2000** [comment]
This does not seem to prevent or delay the crash in my case

**Comment by liushuyu** [comment]
Hi all,

Your issues should have been fixed in mainline 1105. If not, please help us locate your issue by responding to this comment with your (updated) issue description.

 Thanks for everyone here to help us track down the issue!

**Comment by liushuyu** [comment]
Hi everyone,

I will close this issue soon, if you are still experiencing a crash, please reply to this comment, and I will keep this issue open. Thank you.
