### ISSUE TITLE
steam deck yuzu multiple games that worked before now crash

### ISSUE THREAD

**Issue by ohkwon** [flathub/org.yuzu_emu.yuzu#578]

**Comment by purpasmart96** [comment]
Same thing happens in MHGU, on Manjaro KDE linux.

**Comment by Llamamoto** [comment]
Having same problem with links awakening in Manjaro Gnome

**Comment by Llamamoto** [comment]
[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9125016/yuzu_log.txt)

**Comment by aksti** [comment]
Same for Paper Mario und Animal Crossing. Please fix this issue as quickluy as you can. Thanks

[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9126261/yuzu_log.txt)

**Comment by babyborborz** [comment]
Same for Monster Hunter Stories 2, Dragonquest Builders 2

System: Steam Deck

[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9126939/yuzu_log.txt)

**Comment by josejrr1989** [comment]
The same thing happened for Legend of Zelda: Breath of the Wild

**Comment by josejrr1989** [comment]
[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9127748/yuzu_log.txt)

**Comment by liushuyu** [comment]
Hi all, 

Thank you for your report. We have identified the issue and will publish a fix soon.

The issue is in the `dynarmic` CPU JIT module and will only affect the Flatpak version due to the way how Flatpak version is compiled.

**Comment by liushuyu** [comment]
Hi all,

We have (hopefully) fixed the issue in the mainline 1094 version.

I have submitted the new build to FlatHub. It may take a while for FlatHub to make the new release available.

Please test if this new version fixed your issues.

**Comment by ohkwon** [comment]
Thank you for the speedy work and responsiveness! I will definitely test it out!

**Comment by purpasmart96** [comment]
Unfortunately the crash is still present in 1094 for MHGU.

**Comment by babyborborz** [comment]
Same thing for Monster Hunter Stories 2 and Dragonquest Builders 2

**Comment by josejrr1989** [comment]
Still, same problem.

[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9133602/yuzu_log.txt)

**Comment by josejrr1989** [comment]
Still, same problem.

[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9135243/yuzu_log.txt)

**Comment by liushuyu** [comment]
Hi all,

We have identified multiple causes that may have led to the issue. We have fixed one of the issues in the mainline 1096 version.

I have submitted the new build to FlatHub. It may take a while for FlatHub to make the new release available.

Note that the cause of your crash may be different from the other people in this thread. Please test if this new version fixed your issue. If this version still does not fix your issue: don't worry; we are coming up with a speculative fix for the other issues (which will take a while).

**Comment by purpasmart96** [comment]
1096 still crashes MHGU

**Comment by liushuyu** [comment]
> 1096 still crashes MHGU

I see. Then you probably need to wait for the other fix to land in the main repository.

**Comment by aksti** [comment]
Unfortunately the latest Update to version 1096 (2022-07-19) does not help.

Paper Mario, Medroid und Animal Crossing still crashing. Thanks for fixing. 

System: Steam Deck

[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9141534/yuzu_log.txt)

Question, how can I install an older version (e.g. 1089) via flatpak

Thanks

**Comment by Llamamoto** [comment]
This command will roll your package back **sudo flatpak update --commit=003fb91f0bd1b3a23e6111f9d602cb124e74f693ce010a402e3b949c817171dc org.yuzu_emu.yuzu**

**Comment by purpasmart96** [comment]
1098 still the same

**Comment by liushuyu** [comment]
Hi there,

We now have a new fix for the issue. We have prepared a new test version for you: https://github.com/flathub/org.yuzu_emu.yuzu/pull/587#issuecomment-1190778384.

Please test if this fixes the crash you encountered.

Thank you

**Comment by purpasmart96** [comment]
Nope, 1099 same issue.

**Comment by liushuyu** [comment]
> Nope, 1099 same issue, MHGU crashes. Was never a vulkan issue for me since it crashes on opengl too.

Sorry, the fix was not included in 1099. Please click the link: https://github.com/flathub/org.yuzu_emu.yuzu/pull/587#issuecomment-1190778384 for the test build.

**Comment by purpasmart96** [comment]
> > Nope, 1099 same issue, MHGU crashes. Was never a vulkan issue for me since it crashes on opengl too.
> 
> Sorry, the fix was not included in 1099. Please click the link: [#587 (comment)](https://github.com/flathub/org.yuzu_emu.yuzu/pull/587#issuecomment-1190778384) for the test build.
For that build MHGU lasted about 5-7 more seconds before crashing in the same exact manor.

**Comment by purpasmart96** [comment]
> > Nope, 1099 same issue, MHGU crashes. Was never a vulkan issue for me since it crashes on opengl too.
> 
> Sorry, the fix was not included in 1099. Please click the link: [#587 (comment)](https://github.com/flathub/org.yuzu_emu.yuzu/pull/587#issuecomment-1190778384) for the test build.

Still crashing for MHGU, although it lasts about 5-7 seconds longer before hard crashing.

**Comment by Beanow** [comment]
@purpasmart96 are you sure you've tested with with the test version?
Check out my comments on how to run it https://github.com/flathub/org.yuzu_emu.yuzu/issues/570#issuecomment-1192973861

**Comment by ohkwon** [comment]
file:///home/deck/.var/app/org.yuzu_emu.yuzu/data/yuzu/log/yuzu_log.txt__

still crashing atelier ryza, xenoblade 2 and persona 5 strikers on steam deck for v 1100.

**Comment by liushuyu** [comment]
> still crashing atelier ryza, xenoblade 2 and persona 5 strikers on steam deck for v 1100.

1100 is possibly not the test version you are looking for. But don't worry, I will merge the fix into the stable version very soon.

**Comment by ohkwon** [comment]
> > still crashing atelier ryza, xenoblade 2 and persona 5 strikers on steam deck for v 1100.
> 
> 1100 is possibly not the test version you are looking for. But don't worry, I will merge the fix into the stable version very soon.

Noted! Thank you for the update!

**Comment by liushuyu** [comment]
> Noted! Thank you for the update!

I have pushed a new build. The version is still 1100 but with fixes included. Please test if this build fixes your issue.

**Comment by ohkwon** [comment]
> > Noted! Thank you for the update!
> 
> I have pushed a new build. The version is still 1100 but with fixes included. Please test if this build fixes your issue.
[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9172791/yuzu_log.txt)
using flatpak yuzu v 1100, atelier ryza and persona 5 strikers still crashes. xenoblade 2 is working again and dragon quest xi runs better, but with more visual glitches. however, smash ultimate runs at 120 fps now with game speed running at 2x.

**Comment by purpasmart96** [comment]
> @purpasmart96 are you sure you've tested with with the test version? Check out my comments on how to run it [#570 (comment)](https://github.com/flathub/org.yuzu_emu.yuzu/issues/570#issuecomment-1192973861)

Yes, and I'm not doing it again, not sure why you guys want it installed with --user, I had tyo screw around with my flatpak ref because it was under user and not system since installing under user not the default behavior.

**Comment by liushuyu** [comment]
Hi all,

Your issues should have been fixed in mainline 1105. If not, please help us locate your issue by responding to this comment with your (updated) issue description.

 Thanks for everyone here to help us track down the issue!

**Comment by purpasmart96** [comment]
Yeah latest version no crashes!

**Comment by Llamamoto** [comment]
1105 works with Links Awakening:)

**Comment by josejrr1989** [comment]
Breath of the wild is working.

**Comment by ohkwon** [comment]
Any update on when version 1105 will come to flatpak?

**Comment by liushuyu** [comment]
> Any update on when version 1105 will come to flatpak?

1105 has been on Flatpak for a few days now. The latest version here (as of writing) is 1107.

**Comment by ohkwon** [comment]
Currently flatpak via the Discover app in the steam OS linux distro is not showing any update for Yuzu, and I'm currently sitting at version 1100 still. This is probably a config issue on my end then? Or is my understanding  of flatpak incorrect?

**Comment by liushuyu** [comment]
> Currently flatpak via the Discover app in the steam OS linux distro is not showing any update for Yuzu, and I'm currently sitting at version 1100 still. This is probably a config issue on my end then? Or is my understanding of flatpak incorrect?

If you previously installed yuzu test build, please use the following command to remove the reference and repository listing:

```bash
flatpak remote-delete yuzu-origin
flatpak uninstall org.yuzu_emu.yuzu//test
```

**Comment by ohkwon** [comment]
Thanks! I ended up removing yuzu and reinstalling it, at version 1105 now!

Currently, smash ultimate was running at 2x game speed, so i manually had to set the limit speed to 100% (it was at 200% before). Smash ultimate is running fine now.

Xenoblade 2 is also currently running successfully as it did before.

However, Atelier Ryza still crashes when going from title cutscene to main menu that renders 3d assets. 

Persona 5 Strikers is also crashing still, when starting a new game, after clicking okay on a popup icon to dismiss DLC notifications.

[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9193709/yuzu_log.txt)

**Comment by liushuyu** [comment]
> However, Atelier Ryza still crashes when going from title cutscene to main menu that renders 3d assets.
> 
> Persona 5 Strikers is also crashing still, when starting a new game, after clicking okay on a popup icon to dismiss DLC notifications.
> 
> [yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9193709/yuzu_log.txt)

Unfortunately, the log did not capture anything useful.

If you are able, can you help us investigate this further by providing a debugger trace (see https://github.com/flathub/org.yuzu_emu.yuzu/blob/master/README.md#obtaining-a-debugger-trace-after-the-crash)? If you don't know how to use the terminal, then you probably should not attempt this.

**Comment by babyborborz** [comment]
Monster Hunter Stories 2 work on 1105 now. Dragonquest Builders 2 still crashes when starting a new game.

[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9194468/yuzu_log.txt)

**Comment by ohkwon** [comment]
> > However, Atelier Ryza still crashes when going from title cutscene to main menu that renders 3d assets.
> > Persona 5 Strikers is also crashing still, when starting a new game, after clicking okay on a popup icon to dismiss DLC notifications.
> > [yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9193709/yuzu_log.txt)
> 
> Unfortunately, the log did not capture anything useful.
> 
> If you are able, can you help us investigate this further by providing a debugger trace (see https://github.com/flathub/org.yuzu_emu.yuzu/blob/master/README.md#obtaining-a-debugger-trace-after-the-crash)? If you don't know how to use the terminal, then you probably should not attempt this.

When running the following command, following the guide for Obtaining a debugger trace after the crash, I got this error on step 3:

`flatpak-coredumpctl org.yuzu_emu.yuzu -m yuzu --gdb-arguments "--batch -ex 'thread apply all bt'" > /tmp/yuzu-backtrace.log
Executable /app/bin/yuzu doesn't seem to be a flatpaked application.

warning: the debug information found in "/usr/lib/debug//app/bin/yuzu.debug" does not match "/app/bin/yuzu" (CRC mismatch).

BFD: warning: /tmp/tmpb_j_cczv is truncated: expected core file size >= 18279215104, found: 2147483648

warning: Can't open file /memfd:xorg (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:HostMemory (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:xshmfence (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/u1000-Shm_3e474ab8 during file-backed mapping note processing

warning: Can't open file /dev/shm/u1000-Shm_d0c21a95 during file-backed mapping note processing

warning: Can't open file /dev/shm/u1000-Shm_e218bb05 during file-backed mapping note processing

warning: Can't open file /dev/shm/u1000-Shm_d8a3d32f during file-backed mapping note processing

warning: Can't open file /dev/shm/u1000-ValveIPCSharedObj-Steam during file-backed mapping note processing

warning: Error reading shared library list entry at 0x5d7cf8603bee1d0e

warning: Error reading shared library list entry at 0x7f3257c1a18dfee2
Failed to read a valid object file image from memory.
`

**Comment by liushuyu** [comment]
> When running the following command, following the guide for Obtaining a debugger trace after the crash, I got this error on step 3:
> [...]
> warning: the debug information found in "/usr/lib/debug//app/bin/yuzu.debug" does not match "/app/bin/yuzu" (CRC mismatch).

It seems like your yuzu version mismatches the debugging data. But don't worry, one of our developers took an educated guess and worked out a fix. I will publish this fix to the Flatpak version later when I am allowed (by FlatHub) to do so.

**Comment by liushuyu** [comment]
@ohkwon Sorry for the inconvenience. The issue should be fixed in mainline 1112.

**Comment by ohkwon** [comment]
Thanks I can report Atelier Ryza works! I had an issue where all UI elements on screen (mini map, banner text, etc.) was flickering every frame without stop as if the UI couldn't decide which resolution the game was rendering so it was switching locations for the flicker. This went away after switching it from handheld, to docked, to handheld mode again. Not sure what this was, but I thought it was worth mentioning.

I can also report that Persona 5 strikers is now running! but there is a new visual bug where enemies in the beginning are glowing uncharacteristically and it's a rather strong visual effect. I've attached  screenshots below.
[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9230708/yuzu_log.txt)
![20220731202944_1](https://user-images.githubusercontent.com/20409959/182068127-07531819-964b-4740-a0f5-b199ffc7babe.jpg)
![20220731203033_1](https://user-images.githubusercontent.com/20409959/182068137-77c36881-7578-4c85-8488-fe4ee24accf3.jpg)

I've also attached a screenshot of the game of the way it is supposed to look for comparison to give more concrete context. Note the difference in the visuals of the enemy bodies.

![image](https://user-images.githubusercontent.com/20409959/182068304-472c5449-f3ee-4069-88be-58c1829ca6df.png)

Of course, I'm not sure if the yuzu team wants feedback on visual glitches as opposed to hard crashes, so I'll just leave this here in case it is something you do intend to work on. Thank you either way!

**Comment by liushuyu** [comment]
> Of course, I'm not sure if the yuzu team wants feedback on visual glitches as opposed to hard crashes, so I'll just leave this here in case it is something you do intend to work on. Thank you either way!

We do intend to fix both crashes and rendering issues.

However, tracking down rendering issues is very difficult since our developer needs to own either the GPU with the same model (in this case, you can only obtain it by purchasing a Steam Deck) or a similar GPU (in this case, it's challenging to find a similar one). The problem is that the issue may also be stemming from the GPU driver itself doing something unexpected and needing a workaround to prevent it from misinterpreting graphical instructions from yuzu.

**Comment by ohkwon** [comment]
> > Of course, I'm not sure if the yuzu team wants feedback on visual glitches as opposed to hard crashes, so I'll just leave this here in case it is something you do intend to work on. Thank you either way!
> 
> We do intend to fix both crashes and rendering issues.
> 
> However, tracking down rendering issues is very difficult since our developer needs to own either the GPU with the same model (in this case, you can only obtain it by purchasing a Steam Deck) or a similar GPU (in this case, it's challenging to find a similar one). The problem is that the issue may also be stemming from the GPU driver itself doing something unexpected and needing a workaround to prevent it from misinterpreting graphical instructions from yuzu.

Got it, thank you for the explanation. I can also run it on my windows PC and post my results if that will be helpful information for the team!

**Comment by liushuyu** [comment]
Hi, just to do a follow-up. Does the latest yuzu (1253 as of writing) fix the rendering issues in P5S?

**Comment by ohkwon** [comment]
> Hi, just to do a follow-up. Does the latest yuzu (1253 as of writing) fix the rendering issues in P5S?

Hi, thanks for the follow up, I confirmed today that it still has the same graphical issues. It doesn’t freeze when loading though.
