### ISSUE TITLE
Xenoblade Chronicles 2 crashes after moving character a few meters

### ISSUE THREAD

**Issue by xenos9** [flathub/org.yuzu_emu.yuzu#579]
Host: DESKTOP-OJD55MH Kernel: 5.18.11-200.fc36.x86_64 arch: x86_64 bits: 64
    compiler: gcc v: 2.37-27.fc36 Desktop: KDE Plasma v: 5.25.3
    Distro: Fedora release 36 (Thirty Six)
Machine:
  Type: Desktop System: Gigabyte product: Z390 AORUS ULTRA v: N/A
    serial: <superuser required>
  Mobo: Gigabyte model: Z390 AORUS ULTRA-CF v: x.x
    serial: <superuser required> UEFI: American Megatrends v: F7f
    date: 01/16/2019
Battery:
  Device-1: sony_controller_battery_00:22:68:f6:fd:5e model: N/A charge: N/A
    status: full
CPU:
  Info: 8-core model: Intel Core i9-9900K bits: 64 type: MT MCP
    arch: Coffee Lake rev: C cache: L1: 512 KiB L2: 2 MiB L3: 16 MiB
  Speed (MHz): avg: 800 min/max: 800/5000 cores: 1: 800 2: 800 3: 800
    4: 800 5: 800 6: 800 7: 800 8: 800 9: 800 10: 800 11: 800 12: 800 13: 800
    14: 800 15: 800 16: 800 bogomips: 115200
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: NVIDIA TU104 [GeForce RTX 2080 Rev. A] vendor: Micro-Star MSI
    driver: nvidia v: 515.57 arch: Turing bus-ID: 01:00.0
  Device-2: Logitech QuickCam Pro 5000 type: USB
    driver: snd-usb-audio,uvcvideo bus-ID: 1-11.1:7
  Display: x11 server: X.Org v: 1.20.14 with: Xwayland v: 22.1.3 driver: X:
    loaded: nvidia unloaded: fbdev,modesetting,nouveau,vesa
    gpu: nvidia,nvidia-nvswitch resolution: 2560x1440
  OpenGL: renderer: NVIDIA GeForce RTX 2080/PCIe/SSE2
    v: 4.6.0 NVIDIA 515.57 direct render: Yes
Drives:
  Local Storage: total: 6.37 TiB used: 1.39 TiB (21.8%)
Info:
  Processes: 411 Uptime: 15m Memory: 31.19 GiB used: 2.89 GiB (9.3%)
  Init: systemd target: graphical (5) Compilers: gcc: 12.1.1 clang: 14.0.0
  Packages: 19 note: see --pkg Shell: Bash v: 5.1.16 inxi: 3.3.19
[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9125636/yuzu_log.txt)

**Comment by liushuyu** [comment]
Hi there, 

Thank you for your report. We have identified the issue and will publish a fix soon.

The issue is in the `dynarmic` CPU JIT module and will only affect the Flatpak version due to the way how Flatpak version is compiled.

You can temporarily use the AppImage version or downgrade to 1089 as a workaround. Sorry for the inconvenience.

**Comment by liushuyu** [comment]
Hi there,

We have (hopefully) fixed the issue in the mainline 1094 version.

I have submitted the new build to FlatHub. It may take a while for FlatHub to make the new release available.

Please test if this new version fixed your issue.

**Comment by xenos9** [comment]
I'm sorry to say that the issue didn't go away. Now, the crash happens a couple of seconds sooner. 

Problems in other games still persist: 
Fire Emblem TH freezes during loading a save, 
Dragon Quest 11 has a graphical flashing and sometimes the sound goes into resonance.

**Comment by liushuyu** [comment]
> I'm sorry to say that the issue didn't go away. Now, the crash happens a couple of seconds sooner.
> 
> Problems in other games still persist: Fire Emblem TH freezes during loading a save, Dragon Quest 11 has a graphical flashing and sometimes the sound goes into resonance. If you need more logs, let me know and I will add them

I see. Sorry for the inconvenience. We will investigate this further.

**Comment by liushuyu** [comment]
Hi there,

We have identified multiple causes that may have led to the issue. We have fixed one of the issues in the mainline 1096 version.

I have submitted the new build to FlatHub. It may take a while for FlatHub to make the new release available.

Please test if this new version fixed your issue. If this version still does not fix your issue: don't worry; we are coming up with a speculative fix for the other issues (which will take a while).

**Comment by xenos9** [comment]
Sorry to be the bearer of bad new, but the new changes didn't fix the problems that I specified. More so, the graphical glitches in Dragon Quest XI were exacerbated (screen flickering
![Screenshot_20220719_133122](https://user-images.githubusercontent.com/109417480/179731049-7ec2e6d5-dd7c-4c3a-a09b-4ac826ed5514.jpg)
, textures missing and so on
Still, you are doing a great job, don't give up!
(Also, I don't know if I should've opened 3 tickets for 3 different games?)
Also, I will not be able to test and reply in the next couple of weeks

**Comment by CaptainDerank** [comment]
I am not the OP, but I am also have crashes after < 5 seconds.
yuzu 1096 (Flatpak)
System:
  Host: user-linux Kernel: 5.18.9-zen1-1-zen arch: x86_64 bits: 64
    compiler: gcc v: 12.1.0 Desktop: KDE Plasma v: 5.25.2 Distro: Arch Linux
Machine:
  Type: Desktop Mobo: ASUSTeK model: ROG STRIX X570-E GAMING v: Rev X.0x
    serial: <superuser required> UEFI: American Megatrends v: 4021
    date: 08/09/2021
Battery:
  Device-1: ps-controller-battery-xx:xx:xx:xx:xx:xx model: N/A charge: N/A
    status: full
CPU:
  Info: 16-core model: AMD Ryzen 9 5950X bits: 64 type: MT MCP arch: Zen 3
    rev: 0 cache: L1: 1024 KiB L2: 8 MiB L3: 64 MiB
  Speed (MHz): avg: 3716 high: 4483 min/max: 2200/5083 boost: enabled
    cores: 1: 3546 2: 3546 3: 3603 4: 4163 5: 4471 6: 3573 7: 3591 8: 3587
    9: 3581 10: 3609 11: 3532 12: 3536 13: 4426 14: 3532 15: 3555 16: 3535
    17: 3653 18: 3617 19: 3593 20: 3603 21: 3580 22: 3703 23: 4483 24: 3587
    25: 3629 26: 3533 27: 4417 28: 3670 29: 3534 30: 3579 31: 3581 32: 3791
    bogomips: 217203
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] vendor: ASUSTeK
    driver: amdgpu v: kernel arch: RDNA 2 bus-ID: 0d:00.0
  Device-2: NVIDIA GA104 [GeForce RTX 3070] vendor: CardExpert
    driver: vfio-pci v: N/A arch: Ampere bus-ID: 0e:00.0
  Display: wayland server: X.Org v: 22.1.2 with: Xwayland v: 22.1.2
    compositor: kwin_wayland driver: X: loaded: amdgpu unloaded: modesetting
    gpu: amdgpu resolution: 1: 1920x1080~60Hz 2: 3440x1440~144Hz
  OpenGL: renderer: AMD Radeon RX 6900 XT (sienna_cichlid LLVM 14.0.6 DRM
    3.46 5.18.9-zen1-1-zen)
    v: 4.6 Mesa 22.1.3 direct render: Yes
Network:
  Device-1: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel bus-ID: 05:00.0
  IF: wlp5s0 state: down mac: xx:xx:xx:xx:xx:xx
  Device-2: Realtek RTL8125 2.5GbE vendor: ASUSTeK driver: r8169 v: kernel
    port: d000 bus-ID: 06:00.0
  IF: enp6s0 state: up speed: 1000 Mbps duplex: full mac: xx:xx:xx:xx:xx:xx
  Device-3: Intel I211 Gigabit Network vendor: ASUSTeK driver: igb
    v: kernel port: c000 bus-ID: 07:00.0
  IF: enp7s0 state: down mac: xx:xx:xx:xx:xx:xx
  IF-ID-1: team0 state: down mac: xx:xx:xx:xx:xx:xx
Drives:
  Local Storage: total: 8.41 TiB used: 4.47 TiB (53.2%)
Info:
  Processes: 678 Uptime: 12h 51m Memory: 63.15 GiB used: 26.53 GiB (42.0%)
  Init: systemd Compilers: gcc: 12.1.0 clang: 14.0.6 Packages: 2313
  Shell: Zsh v: 5.9 inxi: 3.3.19

[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9144016/yuzu_log.txt)

**Comment by CaptainDerank** [comment]
Ok just saw there was the 1097 Update, but it haven't fixed the crash
[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9144075/yuzu_log.txt)

**Comment by liushuyu** [comment]
Hi all,

We now have a speculative fix for the issue. Since this is a speculative fix, we/I have prepared a test version for you: https://github.com/flathub/org.yuzu_emu.yuzu/pull/587#issuecomment-1189641450.

Please test if this fix at least helps with the crash (e.g. if it delays the crash or makes the crash harder to reproduce).

Thank you

**Comment by CaptainDerank** [comment]
Tried the test build right now, still crashes after <= 5 seconds. So i continue my save, turn around and get a hard lock.

Idk if that helps, but in my terminal following message appeared when it crashes:
`/usr/include/c++/11.3.0/span:278: constexpr std::span<_Type, _Extent>::element_type& std::span<_Type, _Extent>::operator[](std::span<_Type, _Extent>::size_type) const [with _Type = short int; long unsigned int _Extent = 18446744073709551615; std::span<_Type, _Extent>::reference = short int&; std::span<_Type, _Extent>::size_type = long unsigned int]: Assertion '__idx < size()' failed.`

[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9147226/yuzu_log.txt)

**Comment by liushuyu** [comment]
> Tried the test build right now, still crashes after <= 5 seconds. So i continue my save, turn around and get a hard lock.

Sorry but can you verify if Flatpak launched the test version instead of the stable version?

You need to launch the test version using `flatpak run org.yuzu_emu.yuzu//test`. Sorry if this is confusing, this is how Flatpak was designed.

**Comment by liushuyu** [comment]
> I uninstalled the stable version to be sure that it uses the test branch and started it with `flatpak run --branch=test --arch=x86_64 --command=yuzu-launcher org.yuzu_emu.yuzu` and also tried your command `flatpak run org.yuzu_emu.yuzu//test`. Also the version is different, i downgraded yuzu stable to version 1089 so i can progress in the game until the bug is fixed :)
> 
> But to be sure i removed all version of yuzu right now and only installed the linked test build so we could be sure :)
> 
> [yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9147351/yuzu_log.txt)

I see. When you get some time, can you help us track down the issue? Our developers cannot reproduce such a crash. See https://github.com/flathub/org.yuzu_emu.yuzu#obtaining-a-debugger-trace-after-the-crash. Thanks in advance!

**Comment by CaptainDerank** [comment]
Here you go :)

Backtrace using the "After the crash"-method:
[yuzu-backtrace.log](https://github.com/flathub/org.yuzu_emu.yuzu/files/9147634/yuzu-backtrace.log)

Backtrace using the "As the crash happens"-method:
[yuzu-backtrace-while-running.log](https://github.com/flathub/org.yuzu_emu.yuzu/files/9147656/yuzu-backtrace-while-running.log)

**Comment by liushuyu** [comment]
> Here you go :)
> 
> Backtrace using the "After the crash"-method: [yuzu-backtrace.log](https://github.com/flathub/org.yuzu_emu.yuzu/files/9147634/yuzu-backtrace.log)
> 
> Backtrace using the "As the crash happens"-method: [yuzu-backtrace-while-running.log](https://github.com/flathub/org.yuzu_emu.yuzu/files/9147656/yuzu-backtrace-while-running.log)

Thank you very much! However, the debugger did not resolve the function names in the backtrace: this is not your fault: this is a bad design of Flatpak. Can you do `flatpak install --user yuzu-origin org.yuzu_emu.yuzu.Debug` and then try to collect the backtrace again? I will append this information to the instructions. Sorry for the trouble.

**Comment by CaptainDerank** [comment]
No problem, i know how hard it can be to debug such problems :) Unfortunately i am not so familiar with the switch system, else i would try to help to fix the bug :)

[yuzu-backtrace.log](https://github.com/flathub/org.yuzu_emu.yuzu/files/9147877/yuzu-backtrace.log)

**Comment by liushuyu** [comment]
> No problem, i know how hard it can be to debug such problems :) Unfortunately i am not so familiar with the switch system, else i would try to help to fix the bug :)
> 
> [yuzu-backtrace.log](https://github.com/flathub/org.yuzu_emu.yuzu/files/9147877/yuzu-backtrace.log)

Thank you! This shows a very different crash site than we previously thought. The crash seems to be inside the audio decoder. It seems like multiple issues led to this crash.

I have notified the author of this part. We will work out a fix soon.

**Comment by liushuyu** [comment]
Hi there,

We now have a new fix for the issue. We have prepared a new test version for you: https://github.com/flathub/org.yuzu_emu.yuzu/pull/587#issuecomment-1190778384.

Please test if this fixes the crash you encountered.

Thank you

**Comment by CaptainDerank** [comment]
Hi, the new version seems to have fixed the crash. I just downloaded the test build and played for >15 minutes without any crashes :) Thank you :)

**Comment by liushuyu** [comment]
Hi all,

Your issues should have been fixed in mainline 1105. If not, please help us locate your issue by responding to this comment with your (updated) issue description.

 Thanks for everyone here to help us track down the issue!

**Comment by xenos9** [comment]
Sorry for the delay, can confirm that the crash in Xenoblade 2 disappeared, FE loads with no problem.
