### ISSUE TITLE
Almost every game crashes after moving a few meters on Steam Deck now

### ISSUE THREAD

**Issue by Mischiefs** [flathub/org.yuzu_emu.yuzu#582]
Tons of games like Mario kart 8 deluxe, metroid dread and others no longer work on the steam deck when you walk a few meters despite having run flawlessly before and despite running flawlessly on the Yuzu AppImage for version 1091 i downloaded to see if it was a device specific issue.

**Comment by liushuyu** [comment]
Hi all, 

Thank you for your report. We have identified the issue and will publish a fix soon.

The issue is in the `dynarmic` CPU JIT module and will only affect the Flatpak version due to the way how Flatpak version is compiled.

You can temporarily use the AppImage version or downgrade to 1089 as a workaround. Sorry for the inconvenience.

**Comment by Mischiefs** [comment]
Thank you for getting back to me and for working on the fix so soon!

**Comment by liushuyu** [comment]
> Thank you for getting back to me and for working on the fix so soon!

You are welcome! We will update this issue when the fix is confirmed and pushed to the main repository.

**Comment by liushuyu** [comment]
Hi there,

We have (hopefully) fixed the issue in the mainline 1094 version.

I have submitted the new build to FlatHub. It may take a while for FlatHub to make the new release available.

Please test if this new version fixed your issue.

**Comment by MMiX2K** [comment]
The issue is still present :'(

Thanks for all!

**Comment by jorgelukas** [comment]
mario odyssey closed when you walk a few meters, now in the newer version it closes when open the map.

**Comment by liushuyu** [comment]
Hi there,

We have identified multiple causes that may have led to the issue. We have fixed one of the issues in the mainline 1096 version.

I have submitted the new build to FlatHub. It may take a while for FlatHub to make the new release available.

Please test if this new version fixed your issue. If this version still does not fix your issue: don't worry; we are coming up with a speculative fix for the other issues (which will take a while).

**Comment by MMiX2K** [comment]
In my case the issue still persist.

Mario Odyssey crashes when you try yo move, NSMB U Deluxe when the world map appears, Mario 3D World when press continue in screen menu, etc.

Thanks for your work!

**Comment by liushuyu** [comment]
Hi there,

We now have a new fix for the issue. We have prepared a new test version for you: https://github.com/flathub/org.yuzu_emu.yuzu/pull/587#issuecomment-1190778384.

Please test if this fixes the crash you encountered.

Thank you

**Comment by MMiX2K** [comment]
I installed the test version yesterday, but I don't known how to execute it. Flatpack installed version was the same and I didn't found the new in system archives.

I hope that other user can test it.

**Comment by Beanow** [comment]
@MMiX2K I've added details on how to run the test version: https://github.com/flathub/org.yuzu_emu.yuzu/issues/570#issuecomment-1192973861

And for me it improved things. See if that run command helps.

**Comment by liushuyu** [comment]
Hi all,

Your issues should have been fixed in mainline 1105. If not, please help us locate your issue by responding to this comment with your (updated) issue description.

 Thanks for everyone here to help us track down the issue!

**Comment by MMiX2K** [comment]
Yuzu 1105 works like a charm. I tested some games and all of them works ok again.

Thanks!

**Comment by jorgelukas** [comment]
thank you guys for the hard work, version 1105 don't crash immediately, but after 30 minutes playing mario, it crashed.

**Comment by liushuyu** [comment]
> Edit: I've gotten four crashes on Animal Crossing. I will test more deeply.
> 
> Edit 2: The crash it's not present in 1089. It happens when you left the game two minutes without press button and the circle closes to load next screen or when you start the game and they talk to you.

@MMiX2K Can you always replicate the crashes? Or do they happen infrequently?

**Comment by liushuyu** [comment]
> thank you guys for the hard work, version 1105 don't crash immediately, but after 30 minutes playing mario, it crashed. I'm trying to replicate, with the terminal open to see the logs, but it didn't happen again.

@jorgelukas That's pretty problematic. A crash that does not always happen is very difficult to track down. This may indicate external factors like operating system or driver issues.

**Comment by MMiX2K** [comment]
> > Edit: I've gotten four crashes on Animal Crossing. I will test more deeply.
> > Edit 2: The crash it's not present in 1089. It happens when you left the game two minutes without press button and the circle closes to load next screen or when you start the game and they talk to you.
> 
> @MMiX2K Can you always replicate the crashes? Or do they happen infrequently?

Always. I reverted back to 1089 because Animal Crossing crashes when you try to play. I start the game, when the mayor speaks to you, yuzu crashes.

I have not tested more games deeply because I can't play Animal Crossing in Yuzu last version.

**Comment by liushuyu** [comment]
> Edit: I installed 1105 again and uploaded the log.
> [yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9188610/yuzu_log.txt)

The log did not capture anything useful.

And unfortunately, we can't reproduce this issue ourselves, can you help us investigate this further by providing a debugger trace (see https://github.com/flathub/org.yuzu_emu.yuzu/blob/master/README.md#obtaining-a-debugger-trace-after-the-crash)?

Thank you

**Comment by MMiX2K** [comment]
> > Edit: I installed 1105 again and uploaded the log.
> > [yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9188610/yuzu_log.txt)
> 
> The log did not capture anything useful.
> 
> And unfortunately, we can't reproduce this issue ourselves, can you help us investigate this further by providing a debugger trace (see https://github.com/flathub/org.yuzu_emu.yuzu/blob/master/README.md#obtaining-a-debugger-trace-after-the-crash)?
> 
> Thank you

Hi, I have attached two logs. 1 when you press start and 2 when you don't press and wait.

[yuzu_err1.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9203497/yuzu_err1.txt)
[yuzu_err2.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/9203498/yuzu_err2.txt)

**Comment by liushuyu** [comment]
> I tested in most recent version of Yuzu with debugger. In 1089 works flawlessly.
> 
> Seems a problem with audio renderer.

Sorry for the inconvenience. The issue should be fixed in mainline 1112.

**Comment by liushuyu** [comment]
Hi all,

I will close this issue as the problem OP described should have been fixed. Please feel free to open new issues if that is not the case.
